<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS001_LoginAndCreateStore2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>7b1aefe9-e983-4e62-a819-0231f4fac80d</testSuiteGuid>
   <testCaseLink>
      <guid>b79065ee-892e-49c8-b7db-d575e2e5cf48</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC001_LoginShopify</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7fb9466-45cf-4f05-8b84-f8c359033aa6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c539f03d-4a2d-4edf-b3a4-0ded1626fcff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e0475aa-a0ab-4531-9dc0-31a2e27ac6c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>165217ca-b865-4030-a94e-88b198295cd0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fac9552f-7855-4c2e-a18c-14f9864af216</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27678b1a-36e7-447b-8fdd-141642a991b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b65b437-fee3-43f3-92de-850bae1f9ee6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30b1ddcf-bd91-4abb-84fe-fbf24aab9989</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5fe375e5-276e-40f6-8c95-cfec00c853c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC002_CreateStore</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>dd50adb3-35b1-4566-88dd-5c41951948f4</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>2-2</value>
         </iterationEntity>
         <testDataId>Data Files/domain</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88725b8d-f32f-4e17-ad37-98e5a39d85fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab740f74-808c-4972-a4d6-02bb8fe17b6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>551bc31a-a93f-4dc6-8c3b-de6352b1b4a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5822e614-6d5b-4c62-b971-547d6a0ea72e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b44bf12f-e1ff-4b80-aaab-73bbaca755b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dd50adb3-35b1-4566-88dd-5c41951948f4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>domain</value>
         <variableId>91e80cf4-db16-4786-a960-edd629b168c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92c21240-e94e-46d7-8942-4bd16953d7e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ded4699b-0738-4bbd-ba40-62c36e5e8dcb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc59c859-3fd1-42bc-9541-746f222f03e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC003_InstallApp</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3f01590f-84ff-4ef1-abe3-b3417674eb5f</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>2-2</value>
         </iterationEntity>
         <testDataId>Data Files/domain</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>573f2675-b22f-47e3-b80d-d07366259627</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ea8bdd1-6d09-4c43-8b0c-b50a49f92d77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c357a15e-6c3d-48ea-864f-f571ad826faf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae0f2f31-9869-4545-bac1-088cebf51d1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a78a4e8b-6061-432f-af73-b2e2eca4415d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c68deddb-93d3-4821-aafa-caeeefbd981e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c849cf7-01a2-4ddd-bf9e-bb62ba448d65</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3f01590f-84ff-4ef1-abe3-b3417674eb5f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>domain</value>
         <variableId>f6db0e20-7d3f-40e3-9f68-72e19652c43d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
